# SPDX-FileCopyrightText: 2026 aesc silicon
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Fancy
description: Fancy color scheme - vivid flat aesthetic
layers:
  NWELL:
    color: [0.10, 0.30, 0.90, 0.65]
    metallic: 0.00
    roughness: 1.00
  ACTIVE:
    color: [0.10, 0.95, 0.25, 0.90]
    metallic: 0.00
    roughness: 1.00
  GATE:
    color: [0.95, 0.08, 0.08, 0.95]
    metallic: 0.00
    roughness: 1.00
  SDT:
    color: [1.00, 0.52, 0.05, 1.00]
    metallic: 0.00
    roughness: 1.00
  LISD:
    color: [1.00, 0.52, 0.05, 1.00]
    metallic: 0.00
    roughness: 1.00
  LIG:
    color: [1.00, 0.52, 0.05, 1.00]
    metallic: 0.00
    roughness: 1.00
  V0:
    color: [1.00, 1.00, 1.00, 1.00]
    metallic: 0.00
    roughness: 1.00
  M1:
    color: [0.15, 0.40, 1.00, 1.00]
    metallic: 0.00
    roughness: 1.00
  V1:
    color: [1.00, 1.00, 1.00, 1.00]
    metallic: 0.00
    roughness: 1.00
  M2:
    color: [0.35, 0.25, 1.00, 1.00]
    metallic: 0.00
    roughness: 1.00
  V2:
    color: [1.00, 1.00, 1.00, 1.00]
    metallic: 0.00
    roughness: 1.00
  M3:
    color: [0.55, 0.10, 1.00, 1.00]
    metallic: 0.00
    roughness: 1.00
  V3:
    color: [1.00, 1.00, 1.00, 1.00]
    metallic: 0.00
    roughness: 1.00
  M4:
    color: [0.78, 0.09, 0.54, 1.00]
    metallic: 0.00
    roughness: 1.00
  V4:
    color: [1.00, 1.00, 1.00, 1.00]
    metallic: 0.00
    roughness: 1.00
  M5:
    color: [1.00, 0.08, 0.08, 1.00]
    metallic: 0.00
    roughness: 1.00
  V5:
    color: [1.00, 1.00, 1.00, 1.00]
    metallic: 0.00
    roughness: 1.00
  M6:
    color: [1.00, 0.30, 0.07, 1.00]
    metallic: 0.00
    roughness: 1.00
  V6:
    color: [1.00, 1.00, 1.00, 1.00]
    metallic: 0.00
    roughness: 1.00
  M7:
    color: [1.00, 0.52, 0.05, 1.00]
    metallic: 0.00
    roughness: 1.00
  V7:
    color: [1.00, 1.00, 1.00, 1.00]
    metallic: 0.00
    roughness: 1.00
  M8:
    color: [1.00, 0.65, 0.07, 1.00]
    metallic: 0.00
    roughness: 1.00
  V8:
    color: [1.00, 1.00, 1.00, 1.00]
    metallic: 0.00
    roughness: 1.00
  M9:
    color: [1.00, 0.78, 0.10, 1.00]
    metallic: 0.00
    roughness: 1.00
